# Generated by Django 2.2.9 on 2020-07-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200707_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('nome',), 'verbose_name': 'Item de Material', 'verbose_name_plural': 'Itens de Materiais'},
        ),
    ]
