# Generated by Django 2.2.9 on 2020-07-20 19:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_material_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BERCARIO', 'Kit Infantil (Berçário I e II)'), ('MINI_GRUPO', 'Kit Infantil (Mini grupo I e II)'), ('EMEI', 'Kit Infantil (EMEI - Infantil I e II)'), ('CICLO_ALFABETIZACAO', 'Kit Ensino Fundamental - Ciclo alfabetização (1º ao 3º ano)'), ('CICLO_INTERDISCIPLINAR', 'Kit Ensino Fundamental - Ciclo interdisciplinar (4º ao 6º ano)'), ('CICLO_ALTORAL', 'Kit Ensino Fundamental - Ciclo Autoral (7º ao 9º ano)'), ('MEDIO_EJA_MOVA', 'Kit Ensino Médio, EJA e MOVA')], default='CICLO_ALFABETIZACAO', max_length=96),
        ),
    ]
