# Generated by Django 2.2.9 on 2020-07-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_materialkit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='categoria',
        ),
    ]
