# Generated by Django 2.2.9 on 2020-07-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_material_categoria'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kits',
            new_name='Kit',
        ),
    ]
