# Generated by Django 2.2.9 on 2020-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200724_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
    ]
