# Generated by Django 2.2.9 on 2020-07-27 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_kit_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ('nome',), 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
    ]
