# Generated by Django 2.2.9 on 2020-07-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200727_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='preco_maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Preço Máximo'),
        ),
    ]
