# Generated by Django 2.2.9 on 2020-08-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_kit_preco_maximo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ('ordem',), 'verbose_name': 'Kit', 'verbose_name_plural': 'Kits'},
        ),
        migrations.AddField(
            model_name='kit',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
