# Generated by Django 2.2.9 on 2021-03-16 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_parametros_especificacoes_itens_kits'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametros',
            name='email_sme',
            field=models.CharField(default='', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail núcleo para reportar vencimentos de documentos.'),
        ),
    ]
