# Generated by Django 2.2.9 on 2020-07-06 17:36

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cnpj', models.CharField(blank=True, default='', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Digite CNPJ no formato XX.XXX.XXX/XXXX-XX.', regex='(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CNPJ')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('end_logradouro', models.CharField(blank=True, max_length=100, verbose_name='endereço')),
                ('end_cidade', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('end_uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='SP', max_length=2, verbose_name='estado')),
                ('end_cep', models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator(message='Digite o CEP no formato XXXXX-XXX. Com 8 digitos', regex='^\\d{5}-\\d{3}$')], verbose_name='cep')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-]{9,10}$')], verbose_name='Telefone')),
                ('email', models.CharField(blank=True, default='', max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável')),
                ('status', models.CharField(choices=[('INSCRITO', 'Inscrito'), ('BLOQUEADO', 'Bloqueado'), ('EM_PROCESSO', 'Pré-cadastro'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em análise'), ('CREDENCIADO', 'Credenciado')], default='EM_PROCESSO', max_length=15, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Proponente',
                'verbose_name_plural': 'Proponentes',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.TextField(unique=True, verbose_name='Tipo de documento')),
                ('obrigatorio', models.BooleanField(default=True)),
                ('visivel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
        ),
    ]
