# Generated by Django 2.2.9 on 2020-07-06 20:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=100)),
                ('cep', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Digite o CEP no formato XXXXX-XXX. Com 8 digitos', regex='^\\d{5}-\\d{3}$')], verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('numero', models.CharField(blank=True, default='', max_length=255, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('numero_iptu', models.CharField(blank=True, default='', max_length=20, verbose_name='Numero IPTU')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite o telefone no formato (XX) 12345-6789. Entre 8 ou 9 digitos', regex='^\\(\\d{2}\\) [\\d\\-]{9,10}$')], verbose_name='Telefone')),
                ('foto_fachada', models.FileField(blank=True, null=True, upload_to='', verbose_name='Foto da fachada da loja')),
                ('proponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lojas', to='proponentes.Proponente')),
            ],
            options={
                'verbose_name': 'Loja física',
                'verbose_name_plural': 'Lojas físicas',
                'ordering': ('id',),
            },
        ),
    ]
