# Generated by Django 2.2.9 on 2020-07-07 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200707_1145'),
        ('proponentes', '0003_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaDeMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Preço')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proponentes', to='core.Material')),
                ('proponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_de_uniformes', to='proponentes.Proponente')),
            ],
            options={
                'verbose_name': 'oferta de material',
                'verbose_name_plural': 'ofertas de material',
                'unique_together': {('proponente', 'material')},
            },
        ),
    ]
