# Generated by Django 2.2.9 on 2020-07-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0006_auto_20200713_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertadematerial',
            options={'ordering': ('material',), 'verbose_name': 'oferta de material', 'verbose_name_plural': 'ofertas de material'},
        ),
    ]
