# Generated by Django 2.2.9 on 2020-07-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0008_proponente_kits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='kits',
            field=models.ManyToManyField(related_name='proponentes', to='core.Kit'),
        ),
    ]
