# Generated by Django 2.2.9 on 2020-07-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0009_auto_20200729_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='kits',
            field=models.ManyToManyField(blank=True, related_name='proponentes', to='core.Kit'),
        ),
    ]
