# Generated by Django 2.2.9 on 2020-08-03 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0010_auto_20200730_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proponente',
            name='cnpj',
            field=models.CharField(default='', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Digite CNPJ no formato XX.XXX.XXX/XXXX-XX.', regex='(^\\d{2}\\.\\d{3}\\.\\d{3}\\/\\d{4}\\-\\d{2}$)')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='proponente',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
    ]
