# Generated by Django 2.2.9 on 2020-08-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0012_proponente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='proponente',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
