# Generated by Django 2.2.9 on 2020-08-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0013_proponente_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proponente',
            old_name='descricao',
            new_name='observacao',
        ),
    ]
