# Generated by Django 2.2.9 on 2020-08-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0014_auto_20200812_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='tem_data_validade',
            field=models.BooleanField(default=False),
        ),
    ]
