# Generated by Django 2.2.9 on 2020-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0015_auto_20200813_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo',
            name='justificativa',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa'),
        ),
        migrations.AddField(
            model_name='anexo',
            name='status',
            field=models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('PENDENTE', 'Pendente'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=15, verbose_name='status'),
        ),
    ]
