# Generated by Django 2.2.9 on 2021-03-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0018_loja_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='obrigatorio_sme',
            field=models.BooleanField(default=False),
        ),
    ]
