# Generated by Django 2.2.9 on 2022-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0019_tipodocumento_obrigatorio_sme'),
    ]

    operations = [
        migrations.AddField(
            model_name='proponente',
            name='comprovante_end',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Comprovante de Endereço'),
        ),
    ]
