# Generated by Django 2.2.9 on 2022-02-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponentes', '0020_proponente_comprovante_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proponente',
            name='comprovante_end',
        ),
        migrations.AddField(
            model_name='loja',
            name='comprovante_end',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Comprovante de Endereço'),
        ),
    ]
